networks:
  default:
    name: roboshop
    external: true

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
  mongodb:
    build: ./02-mongodb-service
    image: sivaram0101/mongodb-roboshop:v1
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume

  redis:
    build: ./04-redis-service
    image: sivaram0101/redis-roboshop:v1
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  mysql:
    build: ./07-mysql-service
    image: sivaram0101/mysql-roboshop:v1
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
#    Networks:
#      - networkname

  rabbitmq:
    build: ./10-rabbitmq-service
    image: sivaram0101/rabbitmq-roboshop:v1
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
    - "15672:15672" # Management Dashboard port (15672)
    - "5672:5672" # AMQP protocol port (5672)
    volumes:
    - source: rabbitmq
      target: /var/lib/rabbitmq
      type: volume

  catalogue:
    build: ./03-catalogue-service
    image: sivaram0101/catalogue-roboshop:v1
    container_name: catalogue
    depends_on:
    - mongodb

  user:
    build: ./05-user-service
    image: sivaram0101/user-roboshop:v1
    container_name: user
    depends_on:
    - mongodb
    - redis

  cart:
    build: ./06-cart-service
    image: sivaram0101/cart-roboshop:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis

  shipping:
    build: ./08-shipping-service
    image: sivaram0101/shipping-roboshop:v1
    container_name: shipping
    depends_on:
    - mysql

  payment:
    build: ./09-payment-service
    image: sivaram0101/payment-roboshop:v1
    container_name: payment
    environment:
      AMQP_USER: ${AMQP_USER}
      AMQP_PASS: ${AMQP_PASS}
    depends_on:
    - rabbitmq
    - user
    - cart

  frontend:
    build: ./01-frontend-service
    image: sivaram0101/frontend-roboshop:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment