networks:
  default:
    name: roboshop
    external: true

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
  mongodb:
    image: sivaram0101/mongo-roboshop-image:v1
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume

  redis:
    image: sivaram0101/redis-roboshop-image:v1
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  mysql:
    image: sivaram0101/mysql-roboshop-image:v1
    container_name: mysql
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume

  rabbitmq:
    image: sivaram0101/rabbitmq-roboshop-image:v1
    container_name: rabbitmq
    ports:
    - "15672:15672" # Management Dashboard port (15672)
    - "5672:5672" # AMQP protocol port (5672)
    volumes:
    - source: rabbitmq
      target: /var/lib/rabbitmq
      type: volume

  catalogue:
    image: sivaram0101/catalogue-roboshop-image:v1
    container_name: catalogue
    depends_on:
    - mongodb

  cart:
    image: sivaram0101/cart-roboshop-image:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis

  user:
    image: sivaram0101/user-roboshop-image:v1
    container_name: user
    depends_on:
    - mongodb
    - redis

  shipping:
    image: sivaram0101/shipping-roboshop-image:v1
    container_name: shipping
    depends_on:
    - mysql
    
  payment:
    image: sivaram0101/payment-roboshop-image:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - user
    - cart

  frontend:
    image: sivaram0101/frontend-roboshop-image:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment
